project:
  type: website
  

website:
  title: "Windaru's Scribble"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/maswin312
      - icon: linkedin
        href: https://www.linkedin.com/in/windaruw/
format:
  html:
    theme: slate
    css: styles.css
    code-fold: true



