project:
  type: website
  

website:
  title: "Windaru's Scribble"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: morph
    css: styles.css
    code-fold: true



